// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticeProject.Data;

namespace PracticeProject.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20211202223316_AddNavigationProperty")]
    partial class AddNavigationProperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PracticeProject.Models.Expense", b =>
                {
                    b.Property<string>("ExpenseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfExpense")
                        .HasColumnType("datetime2");

                    b.HasKey("ExpenseId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("PracticeProject.Models.ExpenseCategory", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExpenseCategories")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ExpenseId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CategoryId");

                    b.HasIndex("ExpenseId");

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("PracticeProject.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpenseCategoryCategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExpenseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseCategoryCategoryId");

                    b.HasIndex("ExpenseId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PracticeProject.Models.ExpenseCategory", b =>
                {
                    b.HasOne("PracticeProject.Models.Expense", null)
                        .WithMany("ExpenseCategories")
                        .HasForeignKey("ExpenseId");
                });

            modelBuilder.Entity("PracticeProject.Models.User", b =>
                {
                    b.HasOne("PracticeProject.Models.ExpenseCategory", "ExpenseCategory")
                        .WithMany()
                        .HasForeignKey("ExpenseCategoryCategoryId");

                    b.HasOne("PracticeProject.Models.Expense", "Expense")
                        .WithMany("Users")
                        .HasForeignKey("ExpenseId");

                    b.Navigation("Expense");

                    b.Navigation("ExpenseCategory");
                });

            modelBuilder.Entity("PracticeProject.Models.Expense", b =>
                {
                    b.Navigation("ExpenseCategories");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
